# Generated by Django 4.2 on 2023-04-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_level_menuitem_lft_menuitem_rght_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='level',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='tree_id',
        ),
    ]
